src/Entity/Jeu.php
<?php

namespace App\Entity;

use App\Repository\JeuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JeuRepository::class)]
class Jeu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $Titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateSortie = null;

    #[ORM\Column]
    private ?int $note = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $avis = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $dateTest = null;

    #[ORM\Column]
    private ?bool $platine = false;

    #[ORM\Column]
    private ?bool $terminer = false;

    #[ORM\ManyToOne(inversedBy: 'jeu')]
    private ?Categorie $categorie = null;

    #[ORM\ManyToMany(targetEntity: Console::class, mappedBy: 'jeu')]
    private Collection $consoles;

    public function __construct()
    {
        $this->consoles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->dateSortie;
    }

    public function setDateSortie(?\DateTimeInterface $dateSortie): static
    {
        $this->dateSortie = $dateSortie;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getAvis(): ?string
    {
        return $this->avis;
    }

    public function setAvis(string $avis): static
    {
        $this->avis = $avis;

        return $this;
    }

    public function getDateTest(): ?\DateTimeInterface
    {
        return $this->dateTest;
    }

    public function setDateTest(?\DateTimeInterface $dateTest): static
    {
        $this->dateTest = $dateTest;

        return $this;
    }

    public function isPlatine(): ?bool
    {
        return $this->platine;
    }

    public function setPlatine(bool $platine): static
    {
        $this->platine = $platine;

        return $this;
    }

    public function isTerminer(): ?bool
    {
        return $this->terminer;
    }

    public function setTerminer(bool $terminer): static
    {
        $this->terminer = $terminer;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Console>
     */
    public function getConsoles(): Collection
    {
        return $this->consoles;
    }

    public function addConsole(Console $console): static
    {
        if (!$this->consoles->contains($console)) {
            $this->consoles->add($console);
            $console->addJeu($this);
        }

        return $this;
    }

    public function removeConsole(Console $console): static
    {
        if ($this->consoles->removeElement($console)) {
            $console->removeJeu($this);
        }

        return $this;
    }
}

src/Form/JeuType.php
<?php

namespace App\Form;

use App\Entity\Jeu;
use App\Entity\Console;
use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Count;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class JeuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre', TextType::class)
            ->add('consoles', EntityType::class, [
                'class' => Console::class,
                'multiple' => true,
                //'expanded' => true,
                "choice_label" => 'nom',
                'label' => 'Support',
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                "choice_label" => 'nom',
                'label' => 'Genre',
            ])
            ->add('dateSortie', DateType::class, ['widget' => 'single_text', 'attr' => ['class' => 'form-control']])
            ->add('note', NumberType::class)
            ->add('terminer', CheckboxType::class, [
                'label' => 'Arriver au bout du jeu ?', // Facultatif : étiquette de la case à cocher
                'required' => false, // Indique que le champ n'est pas obligatoire
            ])
            ->add('platine', CheckboxType::class, [
                'label' => 'Le jeu a t-il était platiné?', // Facultatif : étiquette de la case à cocher
                'required' => false, // Indique que le champ n'est pas obligatoire
            ])
            ->add('image', FileType::class, [
                'label' =>  'Ajoute une photo',
                'multiple' => false,
                'mapped' => false,
                'required' => false,
                'constraints' => [

                    new File([
                        'maxSize' => '1024k',
                        'maxSizeMessage' => 'La taille maximale autorisée est de {{ limit }}.',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/webp',
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger une image valide (JPEG, PNG, GIF)',
                    ])

                ],
                'label_attr' => ['class' => 'file-label'],
            ])
            ->add('avis', TextareaType::class, [
                'attr' => [
                    'rows' => 8, // Ajustez le nombre de lignes selon vos besoins
                ],
            ])
            //->add('dateTest')
            ->add('Ajouter', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Jeu::class,
        ]);
    }
}

src/Controller/JeuController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Jeu;
use App\Form\JeuType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class JeuController extends AbstractController
{
    #[Route('/jeu', name: 'app_jeu')]
    public function index(ManagerRegistry $doctrine): Response
    {

        $jeux = $doctrine->getRepository(Jeu::class)->findBy([], ["Titre" => "ASC"]);

        return $this->render('jeu/index.html.twig', [
            'jeux' => $jeux,
        ]);
    }

    #[
        Route('/jeu/add', name: 'add_jeu'),
        Route('/jeu/edit/{id}', name: 'edit_jeu')
    ]
    public function add(ManagerRegistry $doctrine, Jeu $jeu = null, Request $request): Response
    {

        if (!$jeu) {
            $jeu = new Jeu();
        }
        $imagePath = $jeu->getImage();

        $form = $this->createForm(JeuType::class, $jeu); // crée mon formulaire à partir du builder EntrepriseType
        $form->handleRequest($request); // quand une action est effectué sur le formulaire, récupère les données

        if ($form->isSubmitted() && $form->isValid()) {
            // on recupere l'image transmise
            $image = $form->get('image')->getData();
            if ($image) {
                // on genere un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // on copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // on stocke l'image dans la base de données
                $jeu->setImage($fichier);
            } else {
                // Aucun nouveau fichier, restaurer le chemin de l'image existante
                $jeu->setImage($imagePath);
            }


            // Récupérer les consoles associées depuis le formulaire
            $consoles = $form->get('consoles')->getData();


            // Associer les consoles au jeu
            foreach ($consoles as $console) {
                $console->addJeu($jeu); // Assurez-vous que cette méthode est correctement définie dans votre entité Console
                $jeu->addConsole($console);
            }


            $now = new DateTime(); // objet date
            $jeu->setDateTest($now); // installe ma date
            $entityManager = $doctrine->getManager();
            $entityManager->persist($jeu);
            $entityManager->flush();

            return $this->redirectToRoute('app_jeu');
        }

        // vue pour formulaire
        return $this->render('jeu/add.html.twig', [
            'formAddJeu' => $form->createView(),
            'edit' => $jeu->getId(), //important pour verifier si employe existe et mettre une condition sur la view
        ]);
    }

    #[Route('/jeu/show/{id}', name: 'show_jeu')]
    public function show(ManagerRegistry $doctrine, Jeu $jeu = null, Request $request): Response
    {
        if ($jeu === null) {
            // Si le produit n'existe pas, redirigez l'utilisateur vers une page d'erreur ou une autre page appropriée.
            return $this->redirectToRoute('app_home');
        }



        return $this->render('jeu/show.html.twig', [
            'controller_name' => 'HomeController',
            'jeu' => $jeu,
        ]);
    }


    #[Route('/jeu/delete/{id}', name: 'delete_jeu')] // supprimer le produit
    public function delete(ManagerRegistry $doctrine, Jeu $jeu = null): Response
    {
        if ($jeu) {

            $entityManager = $doctrine->getManager();

            // Supprimer les images associées
            $image = $jeu->getImage();


            $imagePath = $this->getParameter('images_directory') . '/' . $image;
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
            $entityManager->remove($jeu);



            // Supprimer le jeu
            $entityManager->remove($jeu);
            $entityManager->flush();

            return $this->redirectToRoute('app_jeu');
        } else {
            return $this->redirectToRoute('app_jeu');
        }
    }
}

templates/jeu/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter jeu{% endblock %}

{% block body %}
{% if edit %}
<h1 class="text-2xl text-center my-1 text-orange-400">Editer un jeu</h1>
{% else %}
<h1 class="text-2xl text-center my-1 text-orange-400">Ajouter un jeu</h1>
{% endif %}

<div class="form-jeu">

    {{ form_start(formAddJeu) }}

    {{ form_row(formAddJeu.Titre) }}
    {{ form_row(formAddJeu.consoles) }}
    {{ form_row(formAddJeu.categorie) }}
    {{ form_row(formAddJeu.dateSortie) }}
    {{ form_row(formAddJeu.image) }}
    {{ form_row(formAddJeu.avis) }}
    {{ form_row(formAddJeu.note) }}
    <div class="checkbox">
        {{ form_row(formAddJeu.terminer) }}
    </div>
    <div class="checkbox">
        {{ form_row(formAddJeu.platine) }}
    </div>
    {{ form_row(formAddJeu.Ajouter) }}


    {{ form_end(formAddJeu) }}

</div>

{% endblock %}

templates/jeu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des jeux joués{% endblock %}

{% block body %}

<h1 class="text-2xl text-center text-orange-400 py-3">Liste des jeux testé</h1>


<ul class="w-3/4 flex flex-row gap-5 flex-wrap justify-around mr-auto ml-auto">
    {% for jeu in jeux %}

    <li class="bg-black rounded-t-lg card max-w-xs">
        <figure class="flex flex-col gap-5 items-center justify-between relative">
            <div class="relative">
                <img class="max-w-xs rounded-t-lg h-52" src="{{ asset('uploads/images/' ~ jeu.image) }}"
                    alt="{{ jeu.Titre }}">
                {% if jeu.terminer %}
                <span class="bg-lime-700 text-white jeu-terminer">Terminer</span>
                {% endif %}
            </div>
            {% if jeu.platine %}
            <img class="icone-platine" src="{{asset('uploads/images/ps4-platine.png')}}" alt="platine playstation">
            {% endif %}
            <figcaption class="w-full p-3 ">

                <h2 class="text-xl text-orange-400">{{jeu.Titre}}</h2>
                <p>{{ jeu.dateSortie | date('d/m/Y')}}</p>


                <p class="my-1">Note : {{ jeu.note}}</p>
                <div class="flex gap-5 items-center">
                    <a class="bg-amber-700 text-white py-1.5 px-3 my-1 rounded-md"
                        href="{{path('edit_jeu', { id: jeu.id })}}">Modifier</a>


                    <a href="{{path('show_jeu', {id: jeu.id })}}"
                        class="bg-amber-700 text-white py-1.5 px-2 my-1 rounded-md">Avis</a>
                    <a class="grow text-right" href="{{path('delete_jeu', { id: jeu.id })}}"><i
                            class="fa-solid fa-trash bg-rose-800 p-2.5 rounded-md" style="color: #ffffff;"></i></a>
                </div>
            </figcaption>
        </figure>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/jeu/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter jeu{% endblock %}

{% block body %}

<div class="w-4/5 image-jeu mr-auto ml-auto pt-10 pb-40">
    <img class="w-full" src="{{ asset('uploads/images/' ~ jeu.image) }}" alt="{{ jeu.Titre }}">
    <div class="my-5">
        <h1 class="text-4xl text-center my-1 text-orange-400">{{jeu.titre}}</h1>
        <p class="text-center text-orange-400 italic">Publié le {{ jeu.dateTest | date('d/m/Y')}}</p>
        <p>Date de sortie : {{ jeu.dateSortie | date('d/m/Y')}}</p>
        <p>Genre: {{ jeu.categorie }}</p>
        <div class="flex gap-1 text-white">
            <p>Supports:
            </p>
            {% for console in jeu.consoles %}
            {% if console.nom == "Playstation 5" %}
            <img class="img-logo" src="{{asset('uploads/images/playstation-5.jpg')}}" alt="logo-ps5">
            {% elseif console.nom == "Switch" %}
            <img class="img-logo" src="{{asset('uploads/images/logo-nintendo-switch.png')}}" alt="logo-switch">
            {% elseif console.nom == "Playstation 4" %}
            <img class="img-logo" src="{{asset('uploads/images/PS4-title.jpg')}}" alt="logo-ps4">
            {% elseif console.nom == "PC" %}
            <img class="img-logo" src="{{asset('uploads/images/pc.jpg')}}" alt="logo-pc">
            {% endif %}

            {% endfor %}
        </div>
        <div class="flex gap-1 my-1.5">
            <p>Progression: </p>
            {% if jeu.terminer %}
            <span class="bg-lime-700 text-white px-1.5 py-0.5">Terminer</span>
            {% else %}
            <span class="bg-rose-700 text-white px-1.5 py-0.5">En cours</span>
            {% endif %}
        </div>
        {% if jeu.platine %}
        <div class="text-white flex items-center my-1.5">
            <p>Platine :</p>
            <img class="icone-platine-show" src="{{asset('uploads/images/ps4-platine.png')}}" alt="platine playstation">
        </div>
        {% else %}
        <div class="flex gap-1">
            <p>Platine :</p>
            <p class="bg-rose-700 text-white px-1.5 py-0.5">En cours</p>
        </div>
        {% endif %}
        <p><span class="text-lg font-bold"><span class="text-xl">A</span>vis:</span> {{ jeu.avis }}</p>
        <p class="text-lg font-bold">Note</p>
        {% set note = jeu.note %}

        <div class="set-size charts-container">
            <div class="pie-wrapper progress-{{ note }}">
                <span class="label">{{ note }}<span class="smaller"></span></span>
                <div class="pie" style="{% if jeu.note > 4 %}clip: rect(auto, auto, auto, auto);{% endif %}">
                    <div class="left-side half-circle" style="transform: rotate({{ (note / 10) * 360 }}deg);"></div>
                    <div class="right-side half-circle" style="transform: rotate({{ note > 4 ? 180 : 0 }}deg);"></div>
                </div>
            </div>
        </div>
    </div>



    {% endblock %}